[project]
name = "textstoryreader"
version = "0.1.0"
description = "an app for read text story"
authors = [
    {name = "tdpro1612",email = "hangthieulong508@gmail.com"}
]
packages = [{include = "textstoryreader"}]
readme = "README.md"
requires-python = "==3.10.12"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "==3.10.12"
kivy = "2.3.1"
pyjnius = "1.5.0"
beautifulsoup4 = ">=4.13.4,<5.0.0"
typing-extensions = ">=4.14.1,<5.0.0"

[tool.poetry.group.dev.dependencies]
cython = "0.29.33"
ruff = "^0.12.4"
pylint = "^3.3.7"

[tool.ruff]
line-length = 140

[tool.ruff.lint]
select = ["E", "F", "W", "I"]

[tool.pylint]
disable = [
    "raw-checker-failed",
    "bad-inline-option",
    "locally-disabled",
    "file-ignored",
    "suppressed-message",
    "useless-suppression",
    "deprecated-pragma",
    "use-symbolic-message-instead",
    "W0718", # catching err from try except
    "C0301", # Line too long (Pylint's code for E501 in Ruff)
    "W0201", # Attribute defined outside __init__
    "E1101", # No member (e.g., trying to access a non-existent attribute)
    "E0611", # No name in module (e.g., trying to import a non-existent name)
    "C0103", # Invalid name (e.g., variable names not matching snake_case)
    "C0116", # Missing function or method docstring
    "C0114", # Missing module docstring
    "C0115", # Missing class docstring
    "R0903", # Too few public methods (e.g., a class with only 1-2 methods)
]

max-line-length = 140

